---
  - name: Disable Debian/Ubuntu firewall
    service:
      name: ufw.service
      enabled: no
      state: stopped
    when: iptables.disable_firewall==1

  - name: installing Debian/Ubuntu packages
    package:
      pkg: "{{ deb_packages }}"
      update_cache: yes
    tags: ["common", "packages"]
